version: '3.7'
services:
  neo4j:
    image: neo4j:3.5.29
    container_name: neo4j_amundsen
    environment:
      - NEO4J_AUTH=neo4j/test
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data
    networks:
      - ml_platform

  elasticsearch:
    image: elasticsearch:6.8.18
    container_name: es_amundsen
    ports:
        - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - ml_platform
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  amundsensearch:
    image: amundsendev/amundsen-search:2.11.1
    container_name: amundsensearch
    ports:
      - 5001:5000
    depends_on:
      - elasticsearch
    networks:
      - ml_platform
    environment:
      - PROXY_ENDPOINT=es_amundsen
    command: gunicorn -w 2 --bind :5000 search_service.search_wsgi

  amundsenmetadata:
    image: amundsendev/amundsen-metadata:3.9.0
    container_name: amundsenmetadata
    depends_on:
      - neo4j
    ports:
      - 5002:5000
    networks:
      - ml_platform
    environment:
       - PROXY_HOST=bolt://neo4j_amundsen
    command: gunicorn -w 2 --bind :5000 metadata_service.metadata_wsgi

  amundsenfrontend:
    image: amundsendev/amundsen-frontend:3.12.0
    container_name: amundsenfrontend
    depends_on:
      - amundsenmetadata
      - amundsensearch
    ports:
      - 5000:5000
    networks:
      - ml_platform
    environment:
      - SEARCHSERVICE_BASE=http://amundsensearch:5000
      - METADATASERVICE_BASE=http://amundsenmetadata:5000
      - PREVIEW_CLIENT_ENABLED=${PREVIEW_CLIENT_ENABLED}
      - PREVIEW_CLIENT=${PREVIEW_CLIENT}
      - PREVIEW_CLIENT_URL=${PREVIEW_CLIENT_URL}
      - PREVIEW_CLIENT_USERNAME=${PREVIEW_CLIENT_USERNAME}
      - PREVIEW_CLIENT_PASSWORD=${PREVIEW_CLIENT_PASSWORD}
      # Only for easy config-less Quickstart bookmark evalutation. `TestConfig` extends ordinary `LocalConfig` by
      # defining `AUTH_USER_METHOD` to a hardcoded dummy user in `amundsen_application.tests.test_utils.get_test_user()`
      # See further docs in https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/configuration.md#flask
      # and https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/configuration.md#authentication
      - FRONTEND_SVC_CONFIG_MODULE_CLASS=amundsen_application.config.TestConfig
    command: gunicorn -w 2 --bind :5000 amundsen_application.wsgi

networks:
  ml_platform:
    external: true

volumes:
  es_data:
  neo4j_data:
